version: '3.8'

services:
  deepfake-detector:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./deepfakeImg_detector_1.keras:/app/deepfakeImg_detector_1.keras
    restart: unless-stopped
    container_name: deepfake-detector-app

